version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs-app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs